# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0013_auto_20171113_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprofesor', models.CharField(max_length=80)),
                ('votacion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
